version: '3.8'

services:
  db:
    image: mariadb:10.6
    container_name: attendance_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
      MYSQL_DATABASE: attendance_system
      MYSQL_USER: app_user
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - ./attendance_db:/var/lib/mysql

  api:
    image: ghcr.io/mrdanilp15-crypto/dienstbuch:main
    container_name: attendance_api
    restart: unless-stopped
    environment:
      - DB_PASSWORD=${DB_PASS}
      - ADMIN_PIN=${ADMIN_PIN}
      - USER_PIN=${USER_PIN}
      - TOWN_NAME=${TOWN_NAME}
      - DATABASE_URL=mysql+pymysql://app_user:${DB_PASS}@db/attendance_system
      # Der Pfad innerhalb des Containers für die Notizen
      - SQLITE_DB_PATH=/app/data/notes.db
    ports:
      - "9000:8000"
    volumes:
      - notes_data:/app/data
    depends_on:
      - db

volumes:
  attendance_data:
  notes_data:
